# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9-buster

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - build
  - docs
  - deploy

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .
  - pip install cython
  - pip install libmr # has to be installed after cython
  - pip freeze # print package versions for debugging

test:
  script:
    - python -m unittest discover -s tests
    - pip install coverage
    - coverage run -m unittest discover
    - coverage report -m
    - coverage html
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov/

docs:
  stage: docs
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv _build/html/ ../public/

  artifacts:
    paths:
      - public/

build:
  stage: build
  script:
    - pip install wheel
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

deploy-master:
  stage: deploy
  script:
    - pip install wheel twine
    - python3 setup.py bdist_wheel
    - TWINE_PASSWORD=${TWINE_PASSWORD} TWINE_USERNAME=${TWINE_USER} python -m twine upload dist/*
  allow_failure: true # gitlab does not allow to deploy the same package twice
  artifacts:
    paths:
      - dist/*.whl
  when: manual
  only:
    - master

deploy-inter:
  stage: deploy
  script:
    - pip install wheel twine
    # modify-version
    - sed -i "s/__version__ .*/__version__ = \"${CI_JOB_ID}\"/" src/pytorch_ood/__init__.py
    - rm -r dist/*
    - python3 setup.py bdist_wheel
    - TWINE_PASSWORD=${TWINE_PASSWORD_TEST} TWINE_USERNAME=${TWINE_USER} python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  allow_failure: true # gitlab does not allow to deploy the same package twice
  artifacts:
    paths:
      - dist/*.whl
  when: manual
